@echo off
cd /d "C:\Users\jerry\Documents\GitHub\jerry-gantt-chart"
echo Removing index.lock if exists...
if exist ".git\index.lock" del /f ".git\index.lock"
echo Staging gantt_chart.html...
git add gantt_chart.html
echo Committing...
git commit -m "分享改為 GitHub Pages hash-link，移除 GAS 依賴"
echo Pushing...
git push
echo Done!
pause
